### ISSUE TITLE
unable to run the app

### ISSUE THREAD

**Issue by nitgit121** [john-doherty/node-iframe-replacement#3]
I was trying to setup node-iframe-replacement, but keep getting this error – ‘Unable to retrieve http://www.bbc.co.uk/news’ when i access localhost
 
The exception says - RequestError: Error: getaddrinfo ENOTFOUND www.bbc.co.uk www.bbc.co.uk:80
 
Any idea what’s wrong ?

OS Version : MacOS Sierra : Ver 10.12.5
Chrome : Version 49.0.2623.110 (64-bit)

**Comment by john-doherty** [comment]
Hi @nitgit121, I've just pulled the code and test it and it's working fine for me. 

What version of node are you using?

**Comment by nitgit121** [comment]
{ npm: '3.10.10',
  ares: '1.10.1-DEV',
  http_parser: '2.7.0',
  icu: '58.2',
  modules: '48',
  node: '6.11.1',
  openssl: '1.0.2k',
  uv: '1.11.0',
  v8: '5.1.281.103',
  zlib: '1.2.11' }

**Comment by Geeta-Singh** [comment]
I just pulled and trying to run the code nothing is coming

How to use this ??

**Comment by john-doherty** [comment]
I've pushed a fix and updated the docs with steps to get you up and running with the included example https://github.com/john-doherty/node-iframe-replacement#run-the-example

I've just run it locally and it produced the following:

<img width="1268" alt="screen shot 2018-09-13 at 19 15 01" src="https://user-images.githubusercontent.com/1931833/45507482-28a3e680-b78a-11e8-9822-9233def17d56.png">
