### ISSUE TITLE
How to render a page with in a specified element ?

### ISSUE THREAD

**Issue by TNChalise** [john-doherty/node-iframe-replacement#4]
First of all, this is a very nice node iframe replacement. Is it possible to render the particular web page lets say [bbc.com](http://www.bbc.com/http://www.bbc.com/) inside any element? For instant,

```
 <div or iframe src="parsed.html">
       Content for [bbc.com](http://www.bbc.com/http://www.bbc.com/) 
 </iframe>
```
So that, the exact need of iframe can be replaced ? Please find the attachment for the details.
![screen shot 2017-11-04 at 12 14 51 pm](https://user-images.githubusercontent.com/4486063/32400876-1819093e-c15a-11e7-8c3b-96e954a6423d.png)

**Comment by john-doherty** [comment]
Sorry for the slow response. No, what you're asking for is the reverse of how this module works and not currently possible with this project.
