### ISSUE TITLE
iframes

### ISSUE THREAD

**Issue by examish** [john-doherty/node-iframe-replacement#5]
The other day I was trying to make an iframe for this link for an affiliate program (http://freebitco.in/?r=9171729&tag=wonderland), and I did a test page ([http://wonderlandcoin.com/bitcoin/2.php](http://wonderlandcoin.com/bitcoin/2.php)) and the test uses the Example Domain (example.com) and that works, but when I put in the real URL above, the result is a blank page (http://wonderlandcoin.com/bitcoin/) My question is, did they block the ability for anyone to display their site in an iframe? If so, would your thing help me at all?

**Comment by john-doherty** [comment]
Sounds like they're using iFrame blocking HTTP headers
